import { ExpoConfig, ConfigContext } from "expo/config"

/**
 * Better Rail — Expo app config (CNG source of truth).
 *
 * Native projects (ios/ android/) are git-ignored and regenerated by `expo prebuild`.
 * All native configuration lives here + in ./plugins + in ./targets (apple-targets).
 *
 * APP_VARIANT switches Firebase config between the dev and prod projects, matching the
 * old `rename-dev-configs` npm script. Bundle ids are identical across variants.
 */
const IS_DEV = process.env.APP_VARIANT === "development"

// Shared identifiers consumed by config plugins and targets/*/expo-target.config.js
const APP_GROUP = "group.il.co.better-rail"
const APPLE_TEAM_ID = "UE6BVYPPFX"
const IOS_BUNDLE_ID = "il.co.better-rail"
const ANDROID_PACKAGE = "com.betterrail"

const HEEBO_FONTS = [
  "./assets/fonts/Heebo-Black.otf",
  "./assets/fonts/Heebo-Bold.otf",
  "./assets/fonts/Heebo-ExtraBold.otf",
  "./assets/fonts/Heebo-Light.otf",
  "./assets/fonts/Heebo-Medium.otf",
  "./assets/fonts/Heebo-Regular.otf",
  "./assets/fonts/Heebo-Thin.otf",
]

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: "Better Rail",
  slug: "better-rail",
  version: "2.6.5",
  orientation: "portrait",
  userInterfaceStyle: "automatic",
  icon: "./assets/icons/ios-icon-light.png",
  // App URL scheme + the schemes the app responds to (widget://, liveActivity://)
  scheme: ["betterrail", "widget", "liveActivity"],
  newArchEnabled: true,
  jsEngine: "hermes",
  assetBundlePatterns: ["**/*"],

  ios: {
    bundleIdentifier: IOS_BUNDLE_ID,
    buildNumber: "1",
    // Consumed by @bacons/apple-targets for signing the generated extension/widget/watch targets.
    appleTeamId: APPLE_TEAM_ID,
    supportsTablet: false,
    googleServicesFile: IS_DEV ? "./GoogleService-Info.development.plist" : "./GoogleService-Info.plist",
    icon: {
      light: "./assets/icons/ios-icon-light.png",
      dark: "./assets/icons/ios-icon-dark.png",
      tinted: "./assets/icons/ios-icon-tinted.png",
    },
    infoPlist: {
      LSApplicationQueriesSchemes: ["twitter"],
      NSUserActivityTypes: ["RouteIntent"],
      NSSupportsLiveActivities: true,
      NSSupportsLiveActivitiesFrequentUpdates: true,
      UIBackgroundModes: ["fetch", "remote-notification"],
      NSCalendarsFullAccessUsageDescription: "We need calendar access to add train rides.",
      NSCalendarsUsageDescription: "We need calendar access to add train rides.",
      NSContactsUsageDescription: "We need access to your contacts to import and manage contacts within our app.",
      NSRemindersFullAccessUsageDescription: "We need full access to reminders to create alerts for your train rides.",
      NSRemindersUsageDescription: "Allow $(PRODUCT_NAME) to access your reminders.",
      NSAppTransportSecurity: {
        NSAllowsLocalNetworking: true,
        NSExceptionDomains: {
          localhost: { NSExceptionAllowsInsecureHTTPLoads: true },
        },
      },
    },
    entitlements: {
      "com.apple.security.application-groups": [APP_GROUP],
      "keychain-access-groups": [`$(AppIdentifierPrefix)${APP_GROUP}`],
      "aps-environment": IS_DEV ? "development" : "production",
    },
  },

  android: {
    package: ANDROID_PACKAGE,
    versionCode: 156,
    googleServicesFile: IS_DEV ? "./google-services.development.json" : "./google-services.json",
    allowBackup: false,
    // Widget network calls / local dev (replaces the original network_security_config.xml).
    usesCleartextTraffic: true,
    adaptiveIcon: {
      foregroundImage: "./assets/icons/android-foreground.png",
      backgroundImage: "./assets/icons/android-background.png",
      monochromeImage: "./assets/icons/android-monochrome.png",
    },
    // Widget-specific permissions/components are added by ./plugins/withBetterRailAndroid (Phase 4).
    permissions: [
      "android.permission.INTERNET",
      "com.android.vending.BILLING",
      "android.permission.VIBRATE",
      "android.permission.WAKE_LOCK",
      "android.permission.SCHEDULE_EXACT_ALARM",
      "android.permission.RECEIVE_BOOT_COMPLETED",
      "android.permission.READ_CALENDAR",
      "android.permission.WRITE_CALENDAR",
    ],
    intentFilters: [
      {
        action: "VIEW",
        category: ["DEFAULT", "BROWSABLE"],
        data: [{ scheme: "betterrail" }],
      },
    ],
  },

  plugins: [
    [
      "expo-build-properties",
      {
        ios: {
          deploymentTarget: "16.4",
          useFrameworks: "static",
          // Build React Native from source (matches the original bare project). Required so
          // RCT-Folly is published as a pod — react-native-ios-context-menu/-ios-utilities
          // hard-depend on it, and RN 0.81's prebuilt artifacts don't expose it standalone.
          buildReactNativeFromSource: true,
        },
        android: {
          kotlinVersion: "2.1.20",
          compileSdkVersion: 36,
          targetSdkVersion: 36,
          minSdkVersion: 24,
          enableProguardInReleaseBuilds: false,
        },
      },
    ],
    ["expo-font", { fonts: HEEBO_FONTS }],
    "@react-native-firebase/app",
    [
      "@sentry/react-native/expo",
      {
        organization: process.env.SENTRY_ORG ?? "better-rail",
        project: process.env.SENTRY_PROJECT ?? "better-rail",
        url: "https://sentry.io/",
      },
    ],
    // iOS extension/widget/watch targets live under ./targets (Phase 2)
    "@bacons/apple-targets",
    // Main-app native customizations: Info.plist extras, AppDelegate mods, Podfile post_install (Phase 1)
    "./plugins/withBetterRailIos",
    // Android widget system: Kotlin source, Hilt/Room gradle, manifest, MainApplication/Activity (Phase 4)
    "./plugins/withBetterRailAndroid",
  ],

  extra: {
    eas: {
      // TODO: set EAS project id (`eas init`) before running EAS builds / updates.
      projectId: process.env.EAS_PROJECT_ID ?? "",
    },
    appleTeamId: APPLE_TEAM_ID,
    appGroup: APP_GROUP,
    iosBundleId: IOS_BUNDLE_ID,
    androidPackage: ANDROID_PACKAGE,
  },
})
