import { ExpoConfig, ConfigContext } from "expo/config"

/**
 * Better Rail — Expo app config (CNG source of truth).
 *
 * Native projects (ios/ android/) are git-ignored and regenerated by `expo prebuild`.
 * All native configuration lives here + in ./plugins + in ./targets (apple-targets).
 *
 * APP_VARIANT switches the Android FCM config (google-services.json, dev vs prod Firebase
 * project) and the iOS APNs environment. Bundle ids are identical across variants.
 */
const IS_DEV = process.env.APP_VARIANT === "development"

// Shared identifiers consumed by config plugins and targets/*/expo-target.config.js
const APP_GROUP = "group.il.co.better-rail"
const APPLE_TEAM_ID = "UE6BVYPPFX"
const IOS_BUNDLE_ID = "il.co.better-rail"
const ANDROID_PACKAGE = "com.betterrail"

// iOS registers fonts by the family name baked into each file ("Heebo"), selecting the weight
// via `fontWeight`. The flat string array is all iOS needs.
const HEEBO_FONTS_IOS = [
  "./assets/fonts/Heebo-Black.otf",
  "./assets/fonts/Heebo-Bold.otf",
  "./assets/fonts/Heebo-ExtraBold.otf",
  "./assets/fonts/Heebo-Light.otf",
  "./assets/fonts/Heebo-Medium.otf",
  "./assets/fonts/Heebo-Regular.otf",
  "./assets/fonts/Heebo-Thin.otf",
]

// Android can't weight-select within a family from loose asset files — each file would be its own
// family (e.g. "Heebo-Bold"). The object form makes expo-font emit an XML font resource and call
// ReactFontManager.addCustomFont("Heebo", …), so `fontFamily: "Heebo"` + `fontWeight` resolves to
// the right file natively, matching iOS. (Heebo has no 600/SemiBold file; Android picks the nearest.)
const HEEBO_FONT_ANDROID = {
  fontFamily: "Heebo",
  fontDefinitions: [
    { path: "./assets/fonts/Heebo-Thin.otf", weight: 100 },
    { path: "./assets/fonts/Heebo-Light.otf", weight: 300 },
    { path: "./assets/fonts/Heebo-Regular.otf", weight: 400 },
    { path: "./assets/fonts/Heebo-Medium.otf", weight: 500 },
    { path: "./assets/fonts/Heebo-Bold.otf", weight: 700 },
    { path: "./assets/fonts/Heebo-ExtraBold.otf", weight: 800 },
    { path: "./assets/fonts/Heebo-Black.otf", weight: 900 },
  ],
}

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: "Better Rail",
  slug: "better-rail",
  owner: "better-rail",
  version: "2.7.5",
  updates: {
    url: "https://u.expo.dev/b7819f45-8466-4c11-8628-3539099e6c78",
  },
  // OTA updates only reach builds with the same runtime version (tied to `version` above), so bump
  // `version` whenever the native layer (modules/widgets/plugins/deps) changes — an OTA JS update
  // must never land on an incompatible binary.
  runtimeVersion: {
    policy: "appVersion",
  },
  orientation: "portrait",
  userInterfaceStyle: "automatic",
  icon: "./assets/icons/ios-icon-light.png",
  // App URL scheme + the schemes the app responds to (widget://, liveactivity://)
  // Note: schemes must be lowercase to pass EAS Update manifest validation.
  scheme: ["betterrail", "widget", "liveactivity"],
  jsEngine: "hermes",
  assetBundlePatterns: ["**/*"],

  experiments: {
    reactCompiler: true,
  },

  ios: {
    bundleIdentifier: IOS_BUNDLE_ID,
    buildNumber: "1",
    // Consumed by @bacons/apple-targets for signing the generated extension/widget/watch targets.
    appleTeamId: APPLE_TEAM_ID,
    supportsTablet: false,
    // Icon Composer (Liquid Glass) icon — a string path, per Expo's requirement. The .icon
    // bundle carries its own light/dark/tinted appearance specializations, so it replaces the
    // light/dark/tinted PNG object. Named "AppIcon" (not "Icon") so the project-wide
    // ASSETCATALOG_COMPILER_APPICON_NAME matches the AppIcon set the widget catalog already
    // ships — otherwise the BetterRailWidget archive fails ("no app icon named Icon").
    // (watchOS can't consume .icon — see targets/watch.)
    icon: "./assets/icons/AppIcon.icon",
    infoPlist: {
      // Only standard HTTPS/TLS — exempt encryption (skips export-compliance docs per submission).
      ITSAppUsesNonExemptEncryption: false,
      LSApplicationQueriesSchemes: ["twitter"],
      NSUserActivityTypes: ["RouteIntent"],
      NSSupportsLiveActivities: true,
      NSSupportsLiveActivitiesFrequentUpdates: true,
      UIBackgroundModes: ["fetch", "remote-notification"],
      NSCalendarsFullAccessUsageDescription: "We need calendar access to add train rides.",
      NSCalendarsUsageDescription: "We need calendar access to add train rides.",
      NSContactsUsageDescription: "We need access to your contacts to import and manage contacts within our app.",
      NSRemindersFullAccessUsageDescription: "We need full access to reminders to create alerts for your train rides.",
      NSRemindersUsageDescription: "Allow $(PRODUCT_NAME) to access your reminders.",
      NSAppTransportSecurity: {
        NSAllowsLocalNetworking: true,
        NSExceptionDomains: {
          localhost: { NSExceptionAllowsInsecureHTTPLoads: true },
        },
      },
    },
    entitlements: {
      "com.apple.security.application-groups": [APP_GROUP],
      "keychain-access-groups": [`$(AppIdentifierPrefix)${APP_GROUP}`],
      "aps-environment": IS_DEV ? "development" : "production",
    },
  },

  android: {
    package: ANDROID_PACKAGE,
    versionCode: 157,
    // Prod JSON is git-ignored, so on EAS it comes from a file secret (GOOGLE_SERVICES_JSON);
    // falls back to the local path for on-machine prod prebuilds.
    googleServicesFile: IS_DEV
      ? "./google-services.development.json"
      : (process.env.GOOGLE_SERVICES_JSON ?? "./google-services.json"),
    allowBackup: false,
    // Widget network calls / local dev (replaces the original network_security_config.xml).
    usesCleartextTraffic: true,
    adaptiveIcon: {
      foregroundImage: "./assets/icons/android-foreground.png",
      backgroundImage: "./assets/icons/android-background.png",
      monochromeImage: "./assets/icons/android-monochrome.png",
    },
    // Widget-specific permissions/components are added by ./plugins/withBetterRailAndroid (Phase 4).
    permissions: [
      "android.permission.INTERNET",
      "com.android.vending.BILLING",
      "android.permission.VIBRATE",
      "android.permission.WAKE_LOCK",
      "android.permission.SCHEDULE_EXACT_ALARM",
      "android.permission.RECEIVE_BOOT_COMPLETED",
      "android.permission.READ_CALENDAR",
      "android.permission.WRITE_CALENDAR",
    ],
    intentFilters: [
      {
        action: "VIEW",
        category: ["DEFAULT", "BROWSABLE"],
        data: [{ scheme: "betterrail" }],
      },
    ],
  },

  plugins: [
    "expo-router",
    // Required by react-native-unistyles on Android (edge-to-edge insets via the mini runtime).
    "react-native-edge-to-edge",
    [
      "expo-splash-screen",
      {
        backgroundColor: "#f2f2f7",
        dark: {
          backgroundColor: "#1c1c1e",
        },
        android: {
          image: "./assets/icons/android-foreground.png",
          imageWidth: 180,
        },
      },
    ],
    [
      "expo-build-properties",
      {
        ios: {
          deploymentTarget: "16.4",
          // Build React Native from source (matches the original bare project). Required so
          // RCT-Folly is published as a pod — react-native-ios-context-menu/-ios-utilities
          // hard-depend on it, and RN 0.81's prebuilt artifacts don't expose it standalone.
          // TODO: Switch to use expo/ui instead of the context menu libs
          buildReactNativeFromSource: true,
        },
        android: {
          kotlinVersion: "2.1.20",
          compileSdkVersion: 36,
          targetSdkVersion: 36,
          minSdkVersion: 24,
          enableProguardInReleaseBuilds: false,
        },
      },
    ],
    ["expo-font", { ios: { fonts: HEEBO_FONTS_IOS }, android: { fonts: [HEEBO_FONT_ANDROID] } }],
    // Sole FCM receiver on Android — delivers live-ride data messages (Notifee renders them).
    // The Google Services gradle plugin FCM needs is applied by ./plugins/withBetterRailAndroid
    // (previously came from the @react-native-firebase/app plugin).
    "expo-notifications",
    [
      "@sentry/react-native/expo",
      {
        organization: process.env.SENTRY_ORG ?? "better-rail",
        project: process.env.SENTRY_PROJECT ?? "better-rail",
        url: "https://sentry.io/",
      },
    ],
    // iOS extension/widget/watch targets live under ./targets (Phase 2)
    "@bacons/apple-targets",
    // Main-app native customizations: Info.plist extras, AppDelegate mods, Podfile post_install (Phase 1)
    "./plugins/withBetterRailIos",
    // Android widget system: Kotlin source, Hilt/Room gradle, manifest, MainApplication/Activity (Phase 4)
    "./plugins/withBetterRailAndroid",
  ],

  extra: {
    eas: {
      projectId: process.env.EAS_PROJECT_ID ?? "b7819f45-8466-4c11-8628-3539099e6c78",
    },
    appleTeamId: APPLE_TEAM_ID,
    appGroup: APP_GROUP,
    iosBundleId: IOS_BUNDLE_ID,
    androidPackage: ANDROID_PACKAGE,
  },
})
