/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteImageAttributionsRouteImport } from './routes/_site/image-attributions'
import { Route as SiteIsraelRailwaysLawsuitRouteImport } from './routes/_site/israel-railways-lawsuit'
import { Route as SitePressRouteImport } from './routes/_site/press'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as SiteThankYouRouteImport } from './routes/_site/thank-you'
import { Route as SitemapsPagesRouteImport } from './routes/sitemaps/pages'
import { Route as SitemapsStationsRouteImport } from './routes/sitemaps/stations'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125PrivacyPolicyRouteImport } from './routes/{-$locale}/privacy-policy'
import { Route as SitemapsRoutesPageRouteImport } from './routes/sitemaps/routes.$page'
import { Route as Char123LocaleChar125StationsIndexRouteImport } from './routes/{-$locale}/stations.index'
import { Route as Char123LocaleChar125StationsSlugRouteImport } from './routes/{-$locale}/stations.$slug'
import { Route as Char123LocaleChar125RoutesFromToRouteImport } from './routes/{-$locale}/routes.$from.$to'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteImageAttributionsRoute = SiteImageAttributionsRouteImport.update({
  id: '/image-attributions',
  path: '/image-attributions',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIsraelRailwaysLawsuitRoute =
  SiteIsraelRailwaysLawsuitRouteImport.update({
    id: '/israel-railways-lawsuit',
    path: '/israel-railways-lawsuit',
    getParentRoute: () => SiteRoute,
  } as any)
const SitePressRoute = SitePressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteThankYouRoute = SiteThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => SiteRoute,
} as any)
const SitemapsPagesRoute = SitemapsPagesRouteImport.update({
  id: '/sitemaps/pages',
  path: '/sitemaps/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsStationsRoute = SitemapsStationsRouteImport.update({
  id: '/sitemaps/stations',
  path: '/sitemaps/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PrivacyPolicyRoute =
  Char123LocaleChar125PrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const SitemapsRoutesPageRoute = SitemapsRoutesPageRouteImport.update({
  id: '/sitemaps/routes/$page',
  path: '/sitemaps/routes/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125StationsIndexRoute =
  Char123LocaleChar125StationsIndexRouteImport.update({
    id: '/stations/',
    path: '/stations/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125StationsSlugRoute =
  Char123LocaleChar125StationsSlugRouteImport.update({
    id: '/stations/$slug',
    path: '/stations/$slug',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125RoutesFromToRoute =
  Char123LocaleChar125RoutesFromToRouteImport.update({
    id: '/routes/$from/$to',
    path: '/routes/$from/$to',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/image-attributions': typeof SiteImageAttributionsRoute
  '/israel-railways-lawsuit': typeof SiteIsraelRailwaysLawsuitRoute
  '/press': typeof SitePressRoute
  '/terms': typeof SiteTermsRoute
  '/thank-you': typeof SiteThankYouRoute
  '/sitemaps/pages': typeof SitemapsPagesRoute
  '/sitemaps/stations': typeof SitemapsStationsRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/sitemaps/routes/$page': typeof SitemapsRoutesPageRoute
  '/{-$locale}/stations/$slug': typeof Char123LocaleChar125StationsSlugRoute
  '/{-$locale}/stations/': typeof Char123LocaleChar125StationsIndexRoute
  '/{-$locale}/routes/$from/$to': typeof Char123LocaleChar125RoutesFromToRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/image-attributions': typeof SiteImageAttributionsRoute
  '/israel-railways-lawsuit': typeof SiteIsraelRailwaysLawsuitRoute
  '/press': typeof SitePressRoute
  '/terms': typeof SiteTermsRoute
  '/thank-you': typeof SiteThankYouRoute
  '/sitemaps/pages': typeof SitemapsPagesRoute
  '/sitemaps/stations': typeof SitemapsStationsRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/sitemaps/routes/$page': typeof SitemapsRoutesPageRoute
  '/{-$locale}/stations/$slug': typeof Char123LocaleChar125StationsSlugRoute
  '/{-$locale}/stations': typeof Char123LocaleChar125StationsIndexRoute
  '/{-$locale}/routes/$from/$to': typeof Char123LocaleChar125RoutesFromToRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/image-attributions': typeof SiteImageAttributionsRoute
  '/_site/israel-railways-lawsuit': typeof SiteIsraelRailwaysLawsuitRoute
  '/_site/press': typeof SitePressRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/thank-you': typeof SiteThankYouRoute
  '/sitemaps/pages': typeof SitemapsPagesRoute
  '/sitemaps/stations': typeof SitemapsStationsRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/sitemaps/routes/$page': typeof SitemapsRoutesPageRoute
  '/{-$locale}/stations/$slug': typeof Char123LocaleChar125StationsSlugRoute
  '/{-$locale}/stations/': typeof Char123LocaleChar125StationsIndexRoute
  '/{-$locale}/routes/$from/$to': typeof Char123LocaleChar125RoutesFromToRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/image-attributions'
    | '/israel-railways-lawsuit'
    | '/press'
    | '/terms'
    | '/thank-you'
    | '/sitemaps/pages'
    | '/sitemaps/stations'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/'
    | '/sitemaps/routes/$page'
    | '/{-$locale}/stations/$slug'
    | '/{-$locale}/stations/'
    | '/{-$locale}/routes/$from/$to'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/image-attributions'
    | '/israel-railways-lawsuit'
    | '/press'
    | '/terms'
    | '/thank-you'
    | '/sitemaps/pages'
    | '/sitemaps/stations'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}'
    | '/sitemaps/routes/$page'
    | '/{-$locale}/stations/$slug'
    | '/{-$locale}/stations'
    | '/{-$locale}/routes/$from/$to'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/_site'
    | '/sitemap.xml'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/image-attributions'
    | '/_site/israel-railways-lawsuit'
    | '/_site/press'
    | '/_site/terms'
    | '/_site/thank-you'
    | '/sitemaps/pages'
    | '/sitemaps/stations'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/'
    | '/sitemaps/routes/$page'
    | '/{-$locale}/stations/$slug'
    | '/{-$locale}/stations/'
    | '/{-$locale}/routes/$from/$to'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SitemapsPagesRoute: typeof SitemapsPagesRoute
  SitemapsStationsRoute: typeof SitemapsStationsRoute
  SitemapsRoutesPageRoute: typeof SitemapsRoutesPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/image-attributions': {
      id: '/_site/image-attributions'
      path: '/image-attributions'
      fullPath: '/image-attributions'
      preLoaderRoute: typeof SiteImageAttributionsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/israel-railways-lawsuit': {
      id: '/_site/israel-railways-lawsuit'
      path: '/israel-railways-lawsuit'
      fullPath: '/israel-railways-lawsuit'
      preLoaderRoute: typeof SiteIsraelRailwaysLawsuitRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/press': {
      id: '/_site/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof SitePressRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/thank-you': {
      id: '/_site/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof SiteThankYouRouteImport
      parentRoute: typeof SiteRoute
    }
    '/sitemaps/pages': {
      id: '/sitemaps/pages'
      path: '/sitemaps/pages'
      fullPath: '/sitemaps/pages'
      preLoaderRoute: typeof SitemapsPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/stations': {
      id: '/sitemaps/stations'
      path: '/sitemaps/stations'
      fullPath: '/sitemaps/stations'
      preLoaderRoute: typeof SitemapsStationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/privacy-policy': {
      id: '/{-$locale}/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyPolicyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/sitemaps/routes/$page': {
      id: '/sitemaps/routes/$page'
      path: '/sitemaps/routes/$page'
      fullPath: '/sitemaps/routes/$page'
      preLoaderRoute: typeof SitemapsRoutesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/stations/': {
      id: '/{-$locale}/stations/'
      path: '/stations'
      fullPath: '/{-$locale}/stations/'
      preLoaderRoute: typeof Char123LocaleChar125StationsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/stations/$slug': {
      id: '/{-$locale}/stations/$slug'
      path: '/stations/$slug'
      fullPath: '/{-$locale}/stations/$slug'
      preLoaderRoute: typeof Char123LocaleChar125StationsSlugRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/routes/$from/$to': {
      id: '/{-$locale}/routes/$from/$to'
      path: '/routes/$from/$to'
      fullPath: '/{-$locale}/routes/$from/$to'
      preLoaderRoute: typeof Char123LocaleChar125RoutesFromToRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125PrivacyPolicyRoute: typeof Char123LocaleChar125PrivacyPolicyRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125StationsSlugRoute: typeof Char123LocaleChar125StationsSlugRoute
  Char123LocaleChar125StationsIndexRoute: typeof Char123LocaleChar125StationsIndexRoute
  Char123LocaleChar125RoutesFromToRoute: typeof Char123LocaleChar125RoutesFromToRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125PrivacyPolicyRoute:
      Char123LocaleChar125PrivacyPolicyRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125StationsSlugRoute:
      Char123LocaleChar125StationsSlugRoute,
    Char123LocaleChar125StationsIndexRoute:
      Char123LocaleChar125StationsIndexRoute,
    Char123LocaleChar125RoutesFromToRoute:
      Char123LocaleChar125RoutesFromToRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteImageAttributionsRoute: typeof SiteImageAttributionsRoute
  SiteIsraelRailwaysLawsuitRoute: typeof SiteIsraelRailwaysLawsuitRoute
  SitePressRoute: typeof SitePressRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteThankYouRoute: typeof SiteThankYouRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteImageAttributionsRoute: SiteImageAttributionsRoute,
  SiteIsraelRailwaysLawsuitRoute: SiteIsraelRailwaysLawsuitRoute,
  SitePressRoute: SitePressRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteThankYouRoute: SiteThankYouRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SitemapsPagesRoute: SitemapsPagesRoute,
  SitemapsStationsRoute: SitemapsStationsRoute,
  SitemapsRoutesPageRoute: SitemapsRoutesPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
