/**
 * The stations each line runs through without calling, read off the Service
 * Status map's layout, where every line's route lists the nodes it passes.
 * Writes apps/server/src/status/through-stations.ts, which the service-status
 * extraction uses to charge a suspended stretch to every line on that track.
 *
 *     cd apps/mobile && bun run scripts/rail-service-patterns/through-stations.ts
 *
 * Regenerate it after changing the layout's routes or the line catalogue.
 */
import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { NODES, ROUTES } from "../../src/data/rail-map-layout"
import { RAIL_LINES } from "../../../server/src/status/lines"

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = join(HERE, "../../../server/src/status/through-stations.ts")

const rows = RAIL_LINES.map((line) => {
  const route = ROUTES[line.id].filter((step): step is string => typeof step === "string" && Boolean(NODES[step]?.label))
  const entries: string[] = []
  let after: string | undefined
  for (const stationId of route) {
    if (line.stationIds.includes(stationId)) after = stationId
    else if (after) entries.push(`{ stationId: "${stationId}", after: "${after}" }`)
  }
  return `  "${line.id}": [${entries.length ? `\n    ${entries.join(",\n    ")},\n  ` : ""}],`
})

const source = `/**
 * through-stations.ts — the stations each line runs through without calling, so a suspended
 * stretch is charged to every line whose trains use that track, not only to the lines that
 * call at its ends. Read off the Service Status map's layout, where each line's route lists
 * every station on its track, calling or not.
 *
 * Each entry names the station and the calling station it follows in the line's corridor
 * (\`after\`), so the full corridor can be rebuilt in order — see \`corridorOf\` in lines.ts.
 *
 * Generated by apps/mobile/scripts/rail-service-patterns/through-stations.ts — regenerate rather than hand-edit.
 */
import type { RailLineId } from "./lines"

export type ThroughStation = { stationId: string; after: string }

export const THROUGH_STATIONS: Record<RailLineId, ThroughStation[]> = {
${rows.join("\n")}
}
`
writeFileSync(OUT, source)
console.log(`wrote ${OUT}`)
