/**
 * The service patterns of the Service Status map, from the timetable: which
 * lines run, where their trains call, run through or end short of the line's
 * ends, per day type. Generated by scripts/rail-service-patterns/service-patterns.ts —
 * regenerate rather than hand-edit.
 */
import type { RailLineId } from "./rail-lines"

/**
 * Sunday–Thursday, Friday–Saturday, or the small hours after a weekday: the
 * timetable, and so the map, differs between them.
 */
export type DayType = "weekday" | "weekend" | "night"
/** The day types, in the order the status screen offers them. */
export const DAY_TYPES: DayType[] = ["weekday", "weekend", "night"]

/** Where a line calls, runs through or ends short of its terminus (a line-station pair). */
export type LineStation = { lineId: RailLineId; stationId: string }

export type ServicePattern = {
  /** The lines that run at all. */
  lines: RailLineId[]
  /** Stations a fifth or more of a line's passing trains run through. */
  irregular: LineStation[]
  /** Stations short of a line's ends where a tenth or more of its trains terminate. */
  terminals: LineStation[]
  /** Stations the line runs through without calling at all: no dot, and no name unless another line calls. */
  skipped: LineStation[]
}

/**
 * The service patterns per day type, from the timetable
 * (scripts/rail-service-patterns/station-patterns.json).
 */
export const SERVICE_PATTERNS: Record<DayType, ServicePattern> = {
  weekday: {
    lines: ["1", "10", "11", "12", "2", "25", "3", "3X", "4", "5", "6", "7", "8", "9"],
    irregular: [
      { lineId: "1", stationId: "2500" },
      { lineId: "2", stationId: "5150" },
      { lineId: "3X", stationId: "8550" },
      { lineId: "6", stationId: "4640" },
      { lineId: "6", stationId: "4690" },
    ],
    terminals: [
      { lineId: "11", stationId: "2300" },
      { lineId: "2", stationId: "5200" },
      { lineId: "3", stationId: "3700" },
      { lineId: "3X", stationId: "3700" },
      { lineId: "4", stationId: "1220" },
      { lineId: "5", stationId: "3700" },
      { lineId: "6", stationId: "5800" },
      { lineId: "6", stationId: "5900" },
      { lineId: "6", stationId: "9800" },
    ],
    skipped: [
      { lineId: "1", stationId: "2820" },
      { lineId: "1", stationId: "3100" },
      { lineId: "1", stationId: "3300" },
      { lineId: "1", stationId: "3400" },
      { lineId: "1", stationId: "3500" },
      { lineId: "3", stationId: "1300" },
      { lineId: "3", stationId: "2500" },
      { lineId: "3", stationId: "2800" },
      { lineId: "3", stationId: "700" },
    ],
  },
  weekend: {
    lines: ["1", "10", "11", "2", "3", "4", "5", "6", "7", "8", "9"],
    irregular: [
      { lineId: "1", stationId: "2820" },
      { lineId: "1", stationId: "3100" },
      { lineId: "1", stationId: "3300" },
      { lineId: "1", stationId: "3400" },
      { lineId: "1", stationId: "3500" },
      { lineId: "2", stationId: "3310" },
      { lineId: "2", stationId: "5150" },
      { lineId: "4", stationId: "700" },
      { lineId: "5", stationId: "5150" },
      { lineId: "6", stationId: "2960" },
      { lineId: "6", stationId: "4640" },
      { lineId: "6", stationId: "4690" },
    ],
    terminals: [
      { lineId: "1", stationId: "3700" },
      { lineId: "3", stationId: "3700" },
      { lineId: "6", stationId: "3700" },
    ],
    skipped: [{ lineId: "1", stationId: "700" }],
  },
  night: {
    lines: ["1", "7"],
    irregular: [],
    terminals: [],
    skipped: [
      { lineId: "1", stationId: "1220" },
      { lineId: "1", stationId: "1300" },
      { lineId: "1", stationId: "2200" },
      { lineId: "1", stationId: "2500" },
      { lineId: "1", stationId: "2820" },
      { lineId: "1", stationId: "300" },
      { lineId: "1", stationId: "3400" },
      { lineId: "1", stationId: "3600" },
      { lineId: "1", stationId: "4600" },
      { lineId: "1", stationId: "4900" },
      { lineId: "1", stationId: "700" },
      { lineId: "7", stationId: "3600" },
      { lineId: "7", stationId: "4600" },
      { lineId: "7", stationId: "4900" },
    ],
  },
}
