require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
require File.join(File.dirname(`node --print "require.resolve('react-native-unimodules/package.json')"`), "cocoapods")

platform :ios, '11.0'

target 'BetterRail' do
  use_unimodules!(exclude: ['expo-camera',
  'expo-constants',
  'expo-file-system',
  'expo-image-loader',
  'expo-payments-stripe',
  'expo-permissions',
  'expo-video-thumbnails',
  'unimodules-app-loader',
  'unimodules-barcode-scanner-interface',
  'unimodules-camera-interface',
  'unimodules-constants-interface',  
  'unimodules-face-detector-interface',
  'unimodules-file-system-interface',
  'unimodules-image-loader-interface',
  'unimodules-permissions-interface',
  'unimodules-sensors-interface',
  'unimodules-task-manager-interface'])

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'BetterRailTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()
    post_install do |installer|
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

