# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # export_options: { 
    #   provisioningProfiles: { 
    #     "BetterRail.app": "match AppStore il.co.better-rail",
    #     "WatchBetterRail.app": "match AppStore il.co.better-rail.watchkitapp",
    #     "BetterRailWidgetExtension.appex": "match AppStore il.co.better-rail.BetterRailWidget",
    #     "BetterRailWidgetExtensionWatch.appex": "match AppStore il.co.better-rail.watchkitapp.BetterRailWidget",
    #     "StationIntent.appex": "match AppStore il.co.better-rail.StationIntent", 
    #   }
    # } 
    increment_build_number(xcodeproj: "BetterRail.xcodeproj")
    build_app(workspace: "BetterRail.xcworkspace", scheme: "BetterRail")
    upload_symbols_to_crashlytics
    upload_to_testflight
  end
end
