[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "/routes/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en/routes/*"
  to = "/index.html"
  status = 200
