/**
 * through-stations.ts — the stations each line runs through without calling, so a suspended
 * stretch is charged to every line whose trains use that track, not only to the lines that
 * call at its ends. Read off the Service Status map's geometry, where lines sharing a track
 * are drawn as neighbouring strands: a line without a dot at a station, whose strand runs in
 * that station's bundle, runs through it.
 *
 * Each entry names the station and the calling station it follows in the line's corridor
 * (`after`), so the full corridor can be rebuilt in order — see `corridorOf` in lines.ts.
 *
 * Generated by apps/mobile/scripts/rail-map-trace/through-stations.ts — regenerate rather than hand-edit.
 */
import type { RailLineId } from "./lines"

export type ThroughStation = { stationId: string; after: string }

export const THROUGH_STATIONS: Record<RailLineId, ThroughStation[]> = {
  "1": [{ stationId: "3310", after: "3300" }],
  "2": [],
  "3": [
    { stationId: "2820", after: "2800" },
    { stationId: "3100", after: "2800" },
    { stationId: "3300", after: "2800" },
    { stationId: "3310", after: "2800" },
    { stationId: "3400", after: "2800" },
    { stationId: "4800", after: "4900" },
    { stationId: "5150", after: "4900" },
  ],
  "3X": [
    { stationId: "700", after: "1400" },
    { stationId: "1300", after: "1400" },
    { stationId: "2500", after: "2300" },
    { stationId: "2800", after: "2300" },
    { stationId: "2820", after: "2300" },
    { stationId: "3300", after: "3100" },
    { stationId: "3310", after: "3100" },
    { stationId: "3400", after: "3100" },
    { stationId: "4800", after: "4900" },
    { stationId: "5150", after: "4900" },
    { stationId: "5010", after: "5000" },
    { stationId: "6900", after: "5000" },
    { stationId: "6150", after: "5000" },
  ],
  "4": [],
  "5": [
    { stationId: "3310", after: "3300" },
    { stationId: "4800", after: "4900" },
  ],
  "25": [
    { stationId: "3310", after: "3300" },
    { stationId: "4800", after: "4900" },
    { stationId: "5300", after: "5000" },
  ],
  "6": [],
  "7": [],
  "12": [],
  "9": [{ stationId: "5300", after: "5000" }],
  "10": [],
  "11": [],
  "8": [],
}
