/**
 * Edge caching for server-rendered responses on Cloudflare Workers.
 *
 * Responses generated by a Worker never pass through Cloudflare's CDN cache, so the per-route `CDN-Cache-Control` header
 * (see `cacheHeaders` in `./seo`) is honoured here with the Cache API instead: a 200 GET response is stored for
 * `s-maxage` + `stale-while-revalidate` seconds, served as-is while fresh, then served stale while a background render
 * replaces it. Keys are the full URL (query included), so request headers never influence what is served.
 */

/** The corner of the Cache API we use (`caches.default` on Workers), so tests can supply a fake. */
export interface EdgeCache {
  match(key: Request): Promise<Response | undefined>
  put(key: Request, response: Response): Promise<void>
}

/** The corner of Cloudflare's ExecutionContext we use; `waitUntil` keeps cache writes alive after the response is sent. */
export interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void
}

export interface EdgeCacheOptions {
  /** Absent → no caching (dev, runtimes without the Cache API). */
  cache: EdgeCache | undefined
  ctx?: ExecutionContext
  now?: () => number
}

export interface EdgePolicy {
  sMaxAge: number
  swr: number
}

export type Render = (request: Request) => Promise<Response>

/** On the stored copy: epoch milliseconds until which it is fresh. */
const FRESH_UNTIL = "X-Edge-Fresh-Until"
/** On the stored copy: the `Cache-Control` the browser should get back (the copy's own carries the edge TTL). */
const BROWSER_CACHE_CONTROL = "X-Edge-Browser-Cache-Control"
const DEFAULT_BROWSER_CACHE_CONTROL = "public, max-age=0, must-revalidate"

const directive = (value: string, name: string): number | undefined => {
  const match = new RegExp(`(?:^|,)\\s*${name}=(\\d+)`, "i").exec(value)
  return match ? Number(match[1]) : undefined
}

/** The edge policy of a rendered response, or `null` when it must not be stored. */
export function edgePolicy(response: Response): EdgePolicy | null {
  if (response.status !== 200 || response.headers.has("Set-Cookie")) return null
  const value = response.headers.get("CDN-Cache-Control")
  if (!value || /\b(?:no-store|private)\b/i.test(value)) return null
  const sMaxAge = directive(value, "s-maxage")
  if (!sMaxAge) return null
  return { sMaxAge, swr: directive(value, "stale-while-revalidate") ?? 0 }
}

export function withHeaders(response: Response, headers: Record<string, string>): Response {
  const next = new Response(response.body, response)
  for (const [name, value] of Object.entries(headers)) next.headers.set(name, value)
  return next
}

/** The copy that goes into the cache: kept for the whole fresh + stale window, and marked with when freshness ends. */
function storable(response: Response, policy: EdgePolicy, now: number): Response {
  return withHeaders(response, {
    [BROWSER_CACHE_CONTROL]: response.headers.get("Cache-Control") ?? DEFAULT_BROWSER_CACHE_CONTROL,
    "Cache-Control": `public, s-maxage=${policy.sMaxAge + policy.swr}`,
    [FRESH_UNTIL]: String(now + policy.sMaxAge * 1000),
  })
}

/** A stored copy turned back into what the browser should receive. */
function fromCache(cached: Response, status: "HIT" | "STALE"): Response {
  const response = withHeaders(cached, {
    "Cache-Control": cached.headers.get(BROWSER_CACHE_CONTROL) || DEFAULT_BROWSER_CACHE_CONTROL,
    "X-Edge-Cache": status,
  })
  response.headers.delete(BROWSER_CACHE_CONTROL)
  response.headers.delete(FRESH_UNTIL)
  return response
}

/** Serves `request` from the edge cache when it can, rendering (and storing) it otherwise. */
export async function fetchWithEdgeCache(request: Request, render: Render, options: EdgeCacheOptions): Promise<Response> {
  const { cache, ctx, now = Date.now } = options
  if (!cache || request.method !== "GET") return render(request)

  const key = new Request(request.url, { method: "GET" })
  const store = (response: Response, policy: EdgePolicy) => cache.put(key, storable(response, policy, now()))
  const background = (work: Promise<unknown>) => {
    const settled = work.catch(() => {})
    ctx?.waitUntil(settled)
  }

  const cached = await cache.match(key).catch(() => undefined)
  if (cached) {
    if (Number(cached.headers.get(FRESH_UNTIL)) > now()) return fromCache(cached, "HIT")
    background(
      render(request).then((response) => {
        const policy = edgePolicy(response)
        return policy ? store(response, policy) : response.body?.cancel()
      }),
    )
    return fromCache(cached, "STALE")
  }

  const response = await render(request)
  const policy = edgePolicy(response)
  if (!policy) return response
  background(store(response.clone(), policy))
  return withHeaders(response, { "X-Edge-Cache": "MISS" })
}
