// IDs and Hebrew labels mirror apps/server/src/data/stations.ts; names double as role names.
export const stations = [
  { id: "5800", name: "ad halom", hebrew: "אשדוד עד הלום" },
  { id: "1260", name: "afula", hebrew: "עפולה ר. איתן" },
  { id: "1820", name: "ahihud", hebrew: "אחיהוד" },
  { id: "1500", name: "akko", hebrew: "עכו" },
  { id: "5900", name: "ashkelon", hebrew: "אשקלון" },
  { id: "2500", name: "atlit", hebrew: "עתלית" },
  { id: "2200", name: "bat galim", hebrew: "חיפה - בת גלים" },
  { id: "7320", name: "beer sheva center", hebrew: "באר שבע - מרכז" },
  { id: "7300", name: "beer sheva north university", hebrew: "באר שבע - צפון/אוניברסיטה" },
  { id: "5300", name: "beer yaakov", hebrew: "באר יעקב" },
  { id: "1280", name: "beit shean", hebrew: "בית שאן" },
  { id: "8600", name: "ben gurion", hebrew: "נמל תעופה בן גוריון" },
  { id: "6300", name: "bet shemesh", hebrew: "בית שמש" },
  { id: "3400", name: "bet yehoshua", hebrew: "בית יהושע" },
  { id: "2800", name: "binyamina", hebrew: "בנימינה" },
  { id: "4100", name: "bnei brak", hebrew: "בני ברק" },
  { id: "2820", name: "caesarea pardes hana", hebrew: "קיסריה - פרדס חנה" },
  { id: "7500", name: "dimona", hebrew: "דימונה" },
  { id: "5150", name: "gane aviv", hebrew: "לוד גני אביב" },
  { id: "3900", name: "hadera east", hebrew: "חדרה - מזרח" },
  { id: "3100", name: "hadera west", hebrew: "חדרה - מערב" },
  { id: "4900", name: "hahagana", hebrew: "תל אביב - ההגנה" },
  { id: "1220", name: "hamifrats", hebrew: "מרכזית המפרץ (לב המפרץ)" },
  { id: "9100", name: "harishonim", hebrew: "ראשון לציון - הראשונים" },
  { id: "4600", name: "hashalom", hebrew: "תל אביב - השלום" },
  { id: "2100", name: "hashmona", hebrew: "חיפה - מרכז השמונה" },
  { id: "3500", name: "herzliya", hebrew: "הרצליה" },
  { id: "9200", name: "hod hasharon", hebrew: "הוד השרון - סוקולוב" },
  { id: "2300", name: "hof hakarmel", hebrew: "חיפה - חוף הכרמל" },
  { id: "4640", name: "holon junction", hebrew: "צומת חולון" },
  { id: "1300", name: "hutzot hamifratz", hebrew: "חוצות המפרץ" },
  { id: "1840", name: "karmiel", hebrew: "כרמיאל" },
  { id: "4800", name: "kfar habad", hebrew: 'כפר חב"ד' },
  { id: "8700", name: "kfar saba", hebrew: "כפר סבא - נורדאו" },
  { id: "4170", name: "kiryat arye", hebrew: "פתח תקווה  - קריית אריה" },
  { id: "7000", name: "kiryat gat", hebrew: "קריית גת" },
  { id: "700", name: "kiryat hayim", hebrew: "קריית חיים" },
  { id: "6150", name: "kiryat malakhi yoav", hebrew: "קריית מלאכי - יואב" },
  { id: "1400", name: "kiryat motzkin", hebrew: "קריית מוצקין" },
  { id: "4690", name: "komemiyut", hebrew: "בת ים - קוממיות" },
  { id: "8550", name: "lehavim rahat", hebrew: "להבים - רהט" },
  { id: "5000", name: "lod", hebrew: "לוד" },
  { id: "6900", name: "mazkeret batya", hebrew: "מזכרת בתיה" },
  { id: "1250", name: "migdal haemek kfar barukh", hebrew: "מגדל העמק - כפר ברוך" },
  { id: "400", name: "modiin center", hebrew: "מודיעין - מרכז" },
  { id: "9800", name: "moshe dayan", hebrew: "ראשון לציון - משה דיין" },
  { id: "1600", name: "nahariya", hebrew: "נהריה" },
  { id: "3300", name: "netanya", hebrew: "נתניה" },
  { id: "3310", name: "netanya sapir", hebrew: "נתניה - ספיר" },
  { id: "9650", name: "netivot", hebrew: "נתיבות" },
  { id: "9700", name: "ofakim", hebrew: "אופקים" },
  { id: "300", name: "paate modiin", hebrew: "פאתי מודיעין" },
  { id: "2960", name: "raanana south", hebrew: "רעננה דרום" },
  { id: "2940", name: "raanana west", hebrew: "רעננה מערב" },
  { id: "5010", name: "ramla", hebrew: "רמלה" },
  { id: "5200", name: "rehovot", hebrew: "רחובות" },
  { id: "8800", name: "rosh haayin", hebrew: "ראש העין - צפון" },
  { id: "3700", name: "savidor", hebrew: "תל אביב - סבידור מרכז" },
  { id: "9600", name: "sderot", hebrew: "שדרות" },
  { id: "4250", name: "segula", hebrew: "פתח תקווה - סגולה" },
  { id: "4300", name: "shomron tayyiba", hebrew: "שומרון - טייבה" },
  { id: "4310", name: "tira kokhav yair", hebrew: "טירה - כוכב יאיר" },
  { id: "3600", name: "university", hebrew: "תל אביב - אוניברסיטה" },
  { id: "4660", name: "wolfson", hebrew: "חולון - וולפסון" },
  { id: "5410", name: "yavne east", hebrew: "יבנה מזרח" },
  { id: "9000", name: "yavne west", hebrew: "יבנה מערב" },
  { id: "680", name: "yitzhak navon", hebrew: "ירושלים - יצחק נבון" },
  { id: "1240", name: "yokneam kfar yehoshua", hebrew: "יקנעם - כפר יהושע" },
  { id: "4680", name: "yoseftal", hebrew: "בת ים - יוספטל" },
]
